defaults:
  - nnunet
  - override augmentation: default_2d

batch_size: 4
dataset_name: CAMUS256
do_dummy_2D_data_aug: False
num_workers: 12
patch_size: ${model.net.generator.patch_size}
in_channels: ${get_in_channels_from_model_net:${model.net.generator}}
