defaults:
  - nnunet
  - override augmentation: dealias_2d

_target_: ascent.datamodules.nnunet_dealias_datamodule.nnUNetDealiasDataModule
separate_transform: ${do_separate_transform:${datamodule.in_channels}}
exclude_Dpower: True
batch_size: 4
dataset_name: DEALIASC
do_dummy_2D_data_aug: False
num_workers: 12
