defaults:
  - nnunet

_target_: ascent.datamodules.nnunet_reg_datamodule.nnUNetRegDataModule
seg_label: False

augmentation:
  rotation:
    rotate:
      mode: ${get_interp_mode:${model.net.patch_size},${datamodule.do_dummy_2D_data_aug},"rotation"}
  zoom:
    zoom:
      mode: ${get_interp_mode:${model.net.patch_size},${datamodule.do_dummy_2D_data_aug},"zoom"}
      align_corners: True
