defaults:
  - model_checkpoint
  - latest_checkpoint
  - model_summary
  - rich_progress_bar
  - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "best_epoch_{epoch:03d}"
  monitor: "val/dice_MA"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

latest_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints

model_summary:
  max_depth: -1
