defaults:
  - rotation:
      - rand_rotate
  - zoom:
      - rand_zoom
  - flip:
      - rand_flip_x
      - rand_flip_y
  - noise:
      - rand_gaussian_noise
      - rand_gaussian_smooth
  - intensity:
      - rand_scale_intensity
      - rand_adjust_contrast

rotation:
  rand_rotate:
    mode:
      - ${get_interp_mode:${datamodule.patch_size},${datamodule.do_dummy_2D_data_aug},"rotation"}

zoom:
  rand_zoom:
    mode:
      - ${get_interp_mode:${datamodule.patch_size},${datamodule.do_dummy_2D_data_aug},"zoom"}
    align_corners:
      - True