defaults:
  - model: mnist
  - paths: default
  - override hydra/hydra_logging: disabled
  - _self_

# model checkpoint path
ckpt_path: ???

# path to save the converted ONNX model
onnx_path: ???

# set some default configs to avoid interpolation errors as not all experiment configs are loaded
model:
  scheduler:
    max_decay_steps: 1000
hydra:
  output_subdir: null
  run:
    dir: .
