defaults:
  - preprocessor: segmentation
  - planner:
      - nnunet2d
      - nnunet3d
  - paths: default
  - _self_

# name of dataset, e.g. CAMUS
dataset: ???

# set true to resample the dataset
resample: True

# set true to normalize the dataset
normalize: True

# set true to overwrite the existing cropped folder
overwrite: False

# set true to plan 2D experiment
pl2d: True

# set true to plan 3D experiment
pl3d: True

# set true to print preprocessing message
verbose: False

hydra:
  output_subdir: null
  run:
    dir: .
