rand_zoom:
  _target_: monai.transforms.RandZoomd
  keys: ${datamodule.data_keys.all_keys}
  min_zoom: 0.7
  max_zoom: 1.4
  mode:
    - ${get_interp_mode:${datamodule.patch_size},${datamodule.do_dummy_2D_data_aug},"zoom"}
    - "nearest"
  padding_mode: "constant"
  align_corners:
    - True
    - null # null in yaml is None in python
  prob: 0.2
