_target_: covid.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: covid.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 10

data_params:
  _target_: covid.datamodules.components.dataparams.DataParameters
  in_shape: [1, 28, 28]
  out_shape: [1, 10]
