defaults:
  - net: unet
  - optimizer: sgd
  - scheduler: polylr
  - loss: dice_ce

_target_: ascent.models.nnunet_module.nnUNetLitModule

tta: True
save_predictions: True
save_npz: False
name: nnUNet
