defaults:
  - nnunet
  - override net: pdnet
  - override optimizer: adam
  - override scheduler: coslr
  - override loss: smooth_l1

_target_: ascent.models.nnunet_reg_module.nnUNetRegLitModule
name: PDNetReg

optimizer:
  weight_decay: 0.001

net:
  num_classes: 1
  out_conv: False
