# @package _global_

defaults:
  - _self_
  - datamodule: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - callbacks: default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "eval"

tags: ["eval"]

# desired fold for training
fold: 0

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# 2D or 3D variant of nnUNet
nnUNet_variant: null
