# @package _global_

defaults:
  - _self_
  - datamodule: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist.yaml
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: null

task_name: "eval"

tags: ["dev"]

# desired fold for training
fold: 0

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# 2D or 3D variant of nnUNet
nnUNet_variant: null
