defaults:
  - preprocessor: segmentation
  - planner:
      - nnunet2d
      - nnunet3d
  - paths: default
  - _self_

dataset: ???
resample: True
normalize: True
overwrite: False
pl2d: True
pl3d: True

hydra:
  output_subdir: null
  run:
    dir: .
