_target_: covid.datamodules.nnunet_datamodule.nnUNetDataModule
data_dir: ${paths.data_dir}
batch_size: 2
dataset_name: "CAMUS"
patch_size: ${model.net.patch_size}
in_channels: 1
num_classes: 3
do_dummy_2D_aug: False
do_test: True
fold: ${fold}
