defaults:
  - nnunet

_target_: ascent.datamodules.dealias_datamodule.DealiasDataModule
alias_transform: False
batch_size: 4
dataset_name: DEALIASV
do_dummy_2D_data_aug: False
num_workers: 12
seg_label: False
in_channels: 1
patch_size: ${model.net.patch_size}
