defaults:
  - nnunet

_target_: ascent.datamodules.nnunet_dealias_datamodule.nnUNetDealiasDataModule
alias_transform: False
batch_size: 4
dataset_name: DEALIAS
do_dummy_2D_data_aug: False
num_workers: 12
