defaults:
  - nnunet

net:
  patch_size: [432, 384, 12]
  encoder:
    in_channels: 1
    kernels: [[3, 3, 1], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
    strides: [[1, 1, 1], [2, 2, 1], [2, 2, 2], [2, 2, 1], [2, 2, 1]]
  decoder:
    num_classes: 3
