defaults:
  - nnunet
  - override loss: smooth_l1

_target_: ascent.models.nnunet_reg_module.nnUNetRegLitModule

net:
  patch_size: [40, 192]
  encoder:
    in_channels: 2
    kernels: [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3]]
    strides: [[1, 1], [2, 2], [2, 2], [2, 2], [1, 2]]
  decoder:
    num_classes: 1
    deep_supervision: False

name: nnUNetReg
