# General purpose cropper to produce sub-volume region of interest. Refer to
# https://docs.monai.io/en/latest/transforms.html#SpatialCropd for more details.
_target_: monai.transforms.SpatialCropd
keys: ${datamodule.data_keys.all_keys}
roi_center: null
roi_size: ${get_crop_size:${datamodule.patch_size}}
roi_start: null
roi_end: null
roi_slices: null
allow_missing_keys: False
lazy: False
